### ISSUE TITLE
FAILED EventsByPersistenceIdSpec

### ISSUE THREAD

**Issue by johanandren** [akka/akka-persistence-couchbase#110]
I think it has happened a few times.

```
[info] - must not see new events after demand request *** FAILED *** (13 seconds, 221 milliseconds)
[info]   java.lang.AssertionError: assertion failed: timeout (3 seconds) during expectMsg while waiting for OnNext(e-3)
[info]   at scala.Predef$.assert(Predef.scala:170)
[info]   at akka.testkit.TestKitBase$class.expectMsg_internal(TestKit.scala:402)
[info]   at akka.testkit.TestKitBase$class.expectMsg(TestKit.scala:379)
[info]   at akka.testkit.TestKit.expectMsg(TestKit.scala:896)
[info]   at akka.stream.testkit.TestSubscriber$ManualProbe.expectNext(StreamTestKit.scala:338)
[info]   at akka.persistence.couchbase.EventsByPersistenceIdSpec$$anonfun$1$$anonfun$apply$mcV$sp$5$$anonfun$apply$9.apply(EventsByPersistenceIdSpec.scala:131)
[info]   at akka.persistence.couchbase.EventsByPersistenceIdSpec$$anonfun$1$$anonfun$apply$mcV$sp$5$$anonfun$apply$9.apply(EventsByPersistenceIdSpec.scala:132)
[info]   at akka.testkit.TestKitBase$class.poll$2(TestKit.scala:312)
[info]   at akka.testkit.TestKitBase$class.awaitAssert(TestKit.scala:329)
[info]   at akka.testkit.TestKit.awaitAssert(TestKit.scala:896)
[info]   at akka.persistence.couchbase.EventsByPersistenceIdSpec$$anonfun$1$$anonfun$apply$mcV$sp$5.apply(EventsByPersistenceIdSpec.scala:127)
[info]   at akka.persistence.couchbase.EventsByPersistenceIdSpec$$anonfun$1$$anonfun$apply$mcV$sp$5.apply(EventsByPersistenceIdSpec.scala:112)
```

**Comment by johanandren** [comment]
Another one:

```
[info] - must not see new events after demand request *** FAILED *** (413 milliseconds)
[info]   java.lang.AssertionError: assertion failed: expected OnNext(6-3), found OnComplete
[info]   at scala.Predef$.assert(Predef.scala:170)
[info]   at akka.testkit.TestKitBase$class.expectMsg_internal(TestKit.scala:403)
[info]   at akka.testkit.TestKitBase$class.expectMsg(TestKit.scala:379)
[info]   at akka.testkit.TestKit.expectMsg(TestKit.scala:896)
[info]   at akka.stream.testkit.TestSubscriber$ManualProbe.expectNext(StreamTestKit.scala:338)
[info]   at akka.persistence.couchbase.EventsByPersistenceIdSpec$$anonfun$1$$anonfun$apply$mcV$sp$6$$anon$6.<init>(EventsByPersistenceIdSpec.scala:175)
[info]   at akka.persistence.couchbase.EventsByPersistenceIdSpec$$anonfun$1$$anonfun$apply$mcV$sp$6.apply(EventsByPersistenceIdSpec.scala:154)
[info]   at akka.persistence.couchbase.EventsByPersistenceIdSpec$$anonfun$1$$anonfun$apply$mcV$sp$6.apply(EventsByPersistenceIdSpec.scala:154)
```

**Comment by johanandren** [comment]
Another one in the new test I added:

```
[info] - must not see new events after the query was triggered across page size *** FAILED *** (670 milliseconds)
[info]   java.lang.AssertionError: assertion failed: expected OnNext(7-10), found OnComplete
[info]   at scala.Predef$.assert(Predef.scala:170)
[info]   at akka.testkit.TestKitBase$class.expectMsg_internal(TestKit.scala:403)
[info]   at akka.testkit.TestKitBase$class.expectMsg(TestKit.scala:379)
[info]   at akka.testkit.TestKit.expectMsg(TestKit.scala:896)
[info]   at akka.stream.testkit.TestSubscriber$ManualProbe.expectNext(StreamTestKit.scala:338)
[info]   at akka.persistence.couchbase.EventsByPersistenceIdSpec$$anonfun$1$$anonfun$apply$mcV$sp$7$$anon$7.<init>(EventsByPersistenceIdSpec.scala:213)
[info]   at akka.persistence.couchbase.EventsByPersistenceIdSpec$$anonfun$1$$anonfun$apply$mcV$sp$7.apply(EventsByPersistenceIdSpec.scala:186)
[info]   at akka.persistence.couchbase.EventsByPersistenceIdSpec$$anonfun$1$$anonfun$apply$mcV$sp$7.apply(EventsByPersistenceIdSpec.scala:186)
```
