### ISSUE TITLE
FAILED CouchbaseReadJournalSpec

### ISSUE THREAD

**Issue by johanandren** [akka/akka-persistence-couchbase#116]
`must find existing events with an offset into a batch` just failed locally:

```
[info] - must find existing events with an offset into a batch *** FAILED *** (9 seconds, 986 milliseconds)
[info]   scala.MatchError: EventEnvelope(TimeBasedUUID(2114d8c0-f7d1-11e8-aa95-acde48001122),z1,4,a red bottle) (of class akka.persistence.query.EventEnvelope)
[info]   at akka.persistence.couchbase.CouchbaseReadJournalSpec$$anonfun$4$$anonfun$apply$mcV$sp$8$$anonfun$6.apply(CouchbaseReadJournalSpec.scala:264)
[info]   at akka.persistence.couchbase.CouchbaseReadJournalSpec$$anonfun$4$$anonfun$apply$mcV$sp$8$$anonfun$6.apply(CouchbaseReadJournalSpec.scala:255)
[info]   at akka.testkit.TestKitBase$class.poll$2(TestKit.scala:312)
[info]   at akka.testkit.TestKitBase$class.awaitAssert(TestKit.scala:329)
[info]   at akka.testkit.TestKit.awaitAssert(TestKit.scala:896)
[info]   at akka.persistence.couchbase.CouchbaseReadJournalSpec$$anonfun$4$$anonfun$apply$mcV$sp$8.apply(CouchbaseReadJournalSpec.scala:254)
[info]   at akka.persistence.couchbase.CouchbaseReadJournalSpec$$anonfun$4$$anonfun$apply$mcV$sp$8.apply(CouchbaseReadJournalSpec.scala:241)
[info]   at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
[info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:22)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:20)
[info]   at org.scalatest.WordSpecLike$$anon$1.apply(WordSpecLike.scala:1078)
[info]   at org.scalatest.TestSuite$class.withFixture(TestSuite.scala:196)
[info]   at akka.persistence.couchbase.CouchbaseReadJournalSpec.withFixture(CouchbaseReadJournalSpec.scala:21)
[info]   at org.scalatest.WordSpecLike$class.invokeWithFixture$1(WordSpecLike.scala:1075)
[info]   at org.scalatest.WordSpecLike$$anonfun$runTest$1.apply(WordSpecLike.scala:1088)
[info]   at org.scalatest.WordSpecLike$$anonfun$runTest$1.apply(WordSpecLike.scala:1088)
[info]   at org.scalatest.SuperEngine.runTestImpl(Engine.scala:289)
[info]   at org.scalatest.WordSpecLike$class.runTest(WordSpecLike.scala:1088)
[info]   at akka.persistence.couchbase.CouchbaseReadJournalSpec.org$scalatest$BeforeAndAfterEach$$super$runTest(CouchbaseReadJournalSpec.scala:21)
```

**Comment by johanandren** [comment]
Lets see if #118 fixes this
