### ISSUE TITLE
FAILED EventsByPersistenceId only deliver what requested

### ISSUE THREAD

**Issue by johanandren** [akka/akka-persistence-couchbase#120]
Seen locally

[complete-log.txt](https://github.com/akka/akka-persistence-couchbase/files/2648369/complete-log.txt)

```
[info] - must only deliver what requested if there is more in the buffer *** FAILED *** (11 seconds, 960 milliseconds)
[info]   java.lang.AssertionError: assertion failed: timeout (3 seconds) during expectMsg while waiting for 8-318-done
[info]   at scala.Predef$.assert(Predef.scala:170)
[info]   at akka.testkit.TestKitBase$class.expectMsg_internal(TestKit.scala:402)
[info]   at akka.testkit.TestKitBase$class.expectMsg(TestKit.scala:379)
[info]   at akka.testkit.TestKit.expectMsg(TestKit.scala:896)
[info]   at akka.persistence.couchbase.scaladsl.EventsByPersistenceIdSpec$Setup$$anonfun$startPersistentActor$1.apply(EventsByPersistenceIdSpec.scala:72)
[info]   at akka.persistence.couchbase.scaladsl.EventsByPersistenceIdSpec$Setup$$anonfun$startPersistentActor$1.apply(EventsByPersistenceIdSpec.scala:70)
[info]   at scala.collection.immutable.Range.foreach(Range.scala:160)
[info]   at akka.persistence.couchbase.scaladsl.EventsByPersistenceIdSpec$Setup$class.startPersistentActor(EventsByPersistenceIdSpec.scala:70)
[info]   at akka.persistence.couchbase.scaladsl.EventsByPersistenceIdSpec$$anonfun$1$$anonfun$apply$mcV$sp$8$$anon$8.startPersistentActor(EventsByPersistenceIdSpec.scala:240)
[info]   at akka.persistence.couchbase.scaladsl.EventsByPersistenceIdSpec$Setup$class.$init$(EventsByPersistenceIdSpec.scala:77)
[info]   at akka.persistence.couchbase.scaladsl.EventsByPersistenceIdSpec$$anonfun$1$$anonfun$apply$mcV$sp$8$$anon$8.<init>(EventsByPersistenceIdSpec.scala:240)
[info]   at akka.persistence.couchbase.scaladsl.EventsByPersistenceIdSpec$$anonfun$1$$anonfun$apply$mcV$sp$8.apply(EventsByPersistenceIdSpec.scala:240)
[info]   at akka.persistence.couchbase.scaladsl.EventsByPersistenceIdSpec$$anonfun$1$$anonfun$apply$mcV$sp$8.apply(EventsByPersistenceIdSpec.scala:240)
```

**Comment by johanandren** [comment]
Lets see if #118 fixes this
