### ISSUE TITLE
FAILURE EventsByPersistenceId deliver what requested if there is more in the buffer

### ISSUE THREAD

**Issue by johanandren** [akka/akka-persistence-couchbase#130]
Happened locally:

```
[info] - must only deliver what requested if there is more in the buffer *** FAILED *** (29 seconds, 307 milliseconds)
[info]   java.lang.AssertionError: assertion failed: timeout (3 seconds) during expectMsg while waiting for i-999-done
[info]   at scala.Predef$.assert(Predef.scala:170)
[info]   at akka.testkit.TestKitBase$class.expectMsg_internal(TestKit.scala:402)
[info]   at akka.testkit.TestKitBase$class.expectMsg(TestKit.scala:379)
[info]   at akka.testkit.TestKit.expectMsg(TestKit.scala:896)
[info]   at akka.persistence.couchbase.scaladsl.AbstractQuerySpec$Setup$$anonfun$startPersistentActor$1.apply(AbstractQuerySpec.scala:56)
[info]   at akka.persistence.couchbase.scaladsl.AbstractQuerySpec$Setup$$anonfun$startPersistentActor$1.apply(AbstractQuerySpec.scala:54)
[info]   at scala.collection.immutable.Range.foreach(Range.scala:160)
[info]   at akka.persistence.couchbase.scaladsl.AbstractQuerySpec$Setup$class.startPersistentActor(AbstractQuerySpec.scala:54)
[info]   at akka.persistence.couchbase.scaladsl.EventsByPersistenceIdSpec$$anonfun$2$$anonfun$apply$mcV$sp$18$$anon$18.startPersistentActor(EventsByPersistenceIdSpec.scala:372)
[info]   at akka.persistence.couchbase.scaladsl.AbstractQuerySpec$Setup$class.$init$(AbstractQuerySpec.scala:61)
[info]   at akka.persistence.couchbase.scaladsl.EventsByPersistenceIdSpec$$anonfun$2$$anonfun$apply$mcV$sp$18$$anon$18.<init>(EventsByPersistenceIdSpec.scala:372)
[info]   at akka.persistence.couchbase.scaladsl.EventsByPersistenceIdSpec$$anonfun$2$$anonfun$apply$mcV$sp$18.apply(EventsByPersistenceIdSpec.scala:372)
[info]   at akka.persistence.couchbase.scaladsl.EventsByPersistenceIdSpec$$anonfun$2$$anonfun$apply$mcV$sp$18.apply(EventsByPersistenceIdSpec.scala:372)
[info]   at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
[info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:22)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:20)
[info]   at org.scalatest.WordSpecLike$$anon$1.apply(WordSpecLike.scala:1078)
[info]   at akka.testkit.WithLogCapturing$$anonfun$1.apply(WithLogCapturing.scala:37)
[info]   at akka.testkit.WithLogCapturing$$anonfun$1.apply(WithLogCapturing.scala:35)
[info]   at akka.testkit.EventFilter.intercept(TestEventListener.scala:111)
[info]   at akka.testkit.WithLogCapturing$class.withFixture(WithLogCapturing.scala:35)
[info]   at akka.persistence.couchbase.scaladsl.AbstractQuerySpec.withFixture(AbstractQuerySpec.scala:18)
[info]   at org.scalatest.WordSpecLike$class.invokeWithFixture$1(WordSpecLike.scala:1075)
[info]   at org.scalatest.WordSpecLike$$anonfun$runTest$1.apply(WordSpecLike.scala:1088)
[info]   at org.scalatest.WordSpecLike$$anonfun$runTest$1.apply(WordSpecLike.scala:1088)
[info]   at org.scalatest.SuperEngine.runTestImpl(Engine.scala:289)
[info]   at org.scalatest.WordSpecLike$class.runTest(WordSpecLike.scala:1088)
[info]   at akka.persistence.couchbase.scaladsl.AbstractQuerySpec.runTest(AbstractQuerySpec.scala:18)
[info]   at org.scalatest.WordSpecLike$$anonfun$runTests$1.apply(WordSpecLike.scala:1147)
[info]   at org.scalatest.WordSpecLike$$anonfun$runTests$1.apply(WordSpecLike.scala:1147)
[info]   at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:396)
[info]   at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:384)
[info]   at scala.collection.immutable.List.foreach(List.scala:392)
[info]   at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:384)
[info]   at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:373)
[info]   at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:410)
[info]   at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:384)
[info]   at scala.collection.immutable.List.foreach(List.scala:392)
[info]   at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:384)
[info]   at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:379)
[info]   at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:461)
[info]   at org.scalatest.WordSpecLike$class.runTests(WordSpecLike.scala:1147)
[info]   at akka.persistence.couchbase.scaladsl.AbstractQuerySpec.runTests(AbstractQuerySpec.scala:18)
[info]   at org.scalatest.Suite$class.run(Suite.scala:1147)
[info]   at akka.persistence.couchbase.scaladsl.AbstractQuerySpec.org$scalatest$WordSpecLike$$super$run(AbstractQuerySpec.scala:18)
[info]   at org.scalatest.WordSpecLike$$anonfun$run$1.apply(WordSpecLike.scala:1192)
[info]   at org.scalatest.WordSpecLike$$anonfun$run$1.apply(WordSpecLike.scala:1192)
[info]   at org.scalatest.SuperEngine.runImpl(Engine.scala:521)
[info]   at org.scalatest.WordSpecLike$class.run(WordSpecLike.scala:1192)
[info]   at akka.persistence.couchbase.scaladsl.AbstractQuerySpec.org$scalatest$BeforeAndAfterAll$$super$run(AbstractQuerySpec.scala:18)
[info]   at org.scalatest.BeforeAndAfterAll$class.liftedTree1$1(BeforeAndAfterAll.scala:213)
[info]   at org.scalatest.BeforeAndAfterAll$class.run(BeforeAndAfterAll.scala:210)
[info]   at akka.persistence.couchbase.scaladsl.AbstractQuerySpec.run(AbstractQuerySpec.scala:18)
[info]   at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:314)
[info]   at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:480)
[info]   at sbt.ForkMain$Run.lambda$runTest$1(ForkMain.java:304)
[info]   at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[info]   at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[info]   at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[info]   at java.base/java.lang.Thread.run(Thread.java:834)
```

Full debug log:
[complete-log.txt](https://github.com/akka/akka-persistence-couchbase/files/2656539/complete-log.txt)

**Comment by johanandren** [comment]
Once on travis as well:
[log.txt](https://github.com/akka/akka-persistence-couchbase/files/2736677/log.txt)
