### ISSUE TITLE
FAILED CouchbaseSnapshotSpec

### ISSUE THREAD

**Issue by johanandren** [akka/akka-persistence-couchbase#146]
Reading the writes issue perhaps?

```
--> [A snapshot store must load the most recent snapshot] Start of log messages of test that [Failed(java.lang.AssertionError: assertion failed: expected LoadSnapshotResult(Some(SelectedSnapshot(SnapshotMetadata(p-4,15,1544446479053),s-5)),9223372036854775807), found LoadSnapshotResult(None,9223372036854775807))]
<-- [A snapshot store must load the most recent snapshot] End of log messages of test that [Failed(java.lang.AssertionError: assertion failed: expected LoadSnapshotResult(Some(SelectedSnapshot(SnapshotMetadata(p-4,15,1544446479053),s-5)),9223372036854775807), found LoadSnapshotResult(None,9223372036854775807))]
[info] - must load the most recent snapshot *** FAILED *** (20 milliseconds)
[info]   java.lang.AssertionError: assertion failed: expected LoadSnapshotResult(Some(SelectedSnapshot(SnapshotMetadata(p-4,15,1544446479053),s-5)),9223372036854775807), found LoadSnapshotResult(None,9223372036854775807)
[info]   at scala.Predef$.assert(Predef.scala:170)
[info]   at akka.testkit.TestKitBase$class.expectMsg_internal(TestKit.scala:403)
[info]   at akka.testkit.TestKitBase$class.expectMsg(TestKit.scala:379)
[info]   at akka.testkit.TestKit.expectMsg(TestKit.scala:896)
[info]   at akka.persistence.snapshot.SnapshotStoreSpec$$anonfun$1$$anonfun$apply$mcV$sp$5.apply(SnapshotStoreSpec.scala:93)
[info]   at akka.persistence.snapshot.SnapshotStoreSpec$$anonfun$1$$anonfun$apply$mcV$sp$5.apply(SnapshotStoreSpec.scala:91)
[info]   at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
[info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:22)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:20)
[info]   at org.scalatest.WordSpecLike$$anon$1.apply(WordSpecLike.scala:1078)
[info]   at akka.testkit.WithLogCapturing$$anonfun$1.apply(WithLogCapturing.scala:37)
[info]   at akka.testkit.WithLogCapturing$$anonfun$1.apply(WithLogCapturing.scala:35)
[info]   at akka.testkit.EventFilter.intercept(TestEventListener.scala:111)
[info]   at akka.testkit.WithLogCapturing$class.withFixture(WithLogCapturing.scala:35)
[info]   at akka.persistence.couchbase.CouchbaseSnapshotStoreSpec.withFixture(CouchbaseSnapshotStoreSpec.scala:11)
```

**Comment by johanandren** [comment]
```
-> [A snapshot store must load the most recent snapshot] Start of log messages of test that [Failed(java.lang.AssertionError: assertion failed: expected LoadSnapshotResult(Some(SelectedSnapshot(SnapshotMetadata(p-4,15,1551136842552),s-5)),9223372036854775807), found LoadSnapshotResult(None,9223372036854775807))]
<-- [A snapshot store must load the most recent snapshot] End of log messages of test that [Failed(java.lang.AssertionError: assertion failed: expected LoadSnapshotResult(Some(SelectedSnapshot(SnapshotMetadata(p-4,15,1551136842552),s-5)),9223372036854775807), found LoadSnapshotResult(None,9223372036854775807))]
[info] - must load the most recent snapshot *** FAILED *** (35 milliseconds)
[info]   java.lang.AssertionError: assertion failed: expected LoadSnapshotResult(Some(SelectedSnapshot(SnapshotMetadata(p-4,15,1551136842552),s-5)),9223372036854775807), found LoadSnapshotResult(None,9223372036854775807)
[info]   at scala.Predef$.assert(Predef.scala:170)
[info]   at akka.testkit.TestKitBase$class.expectMsg_internal(TestKit.scala:403)
[info]   at akka.testkit.TestKitBase$class.expectMsg(TestKit.scala:379)
[info]   at akka.testkit.TestKit.expectMsg(TestKit.scala:896)
[info]   at akka.persistence.snapshot.SnapshotStoreSpec$$anonfun$1$$anonfun$apply$mcV$sp$5.apply(SnapshotStoreSpec.scala:93)
[info]   at akka.persistence.snapshot.SnapshotStoreSpec$$anonfun$1$$anonfun$apply$mcV$sp$5.apply(SnapshotStoreSpec.scala:91)
```

**Comment by johanandren** [comment]
```
--> [A snapshot store must load the most recent snapshot] Start of log messages of test that [Failed(java.lang.AssertionError: assertion failed: expected LoadSnapshotResult(Some(SelectedSnapshot(SnapshotMetadata(p-4,15,1557128730779),s-5)),9223372036854775807), found LoadSnapshotResult(None,9223372036854775807))]
<-- [A snapshot store must load the most recent snapshot] End of log messages of test that [Failed(java.lang.AssertionError: assertion failed: expected LoadSnapshotResult(Some(SelectedSnapshot(SnapshotMetadata(p-4,15,1557128730779),s-5)),9223372036854775807), found LoadSnapshotResult(None,9223372036854775807))]
[info] - must load the most recent snapshot *** FAILED *** (37 milliseconds)
[info]   java.lang.AssertionError: assertion failed: expected LoadSnapshotResult(Some(SelectedSnapshot(SnapshotMetadata(p-4,15,1557128730779),s-5)),9223372036854775807), found LoadSnapshotResult(None,9223372036854775807)
[info]   at scala.Predef$.assert(Predef.scala:223)
[info]   at akka.testkit.TestKitBase.expectMsg_internal(TestKit.scala:403)
[info]   at akka.testkit.TestKitBase.expectMsg(TestKit.scala:379)
[info]   at akka.testkit.TestKitBase.expectMsg$(TestKit.scala:379)
[info]   at akka.testkit.TestKit.expectMsg(TestKit.scala:896)
[info]   at akka.persistence.snapshot.SnapshotStoreSpec.$anonfun$new$5(SnapshotStoreSpec.scala:93)
```
