### ISSUE TITLE
Failed: EventsByPersistenceIdSpec

### ISSUE THREAD

**Issue by johanandren** [akka/akka-persistence-couchbase#187]
https://api.travis-ci.org/v3/job/476499839/log.txt

```
 must skip deleted events *** FAILED *** (9 seconds, 892 milliseconds)
[info]   java.lang.AssertionError: assertion failed: expected OnNext(2-3), found OnComplete
[info]   at scala.Predef$.assert(Predef.scala:170)
[info]   at akka.testkit.TestKitBase$class.expectMsg_internal(TestKit.scala:403)
[info]   at akka.testkit.TestKitBase$class.expectMsg(TestKit.scala:379)
[info]   at akka.testkit.TestKit.expectMsg(TestKit.scala:896)
[info]   at akka.stream.testkit.TestSubscriber$ManualProbe.expectNext(StreamTestKit.scala:338)
[info]   at akka.persistence.couchbase.scaladsl.EventsByPersistenceIdSpec$$anonfun$1$$anonfun$apply$mcV$sp$2$$anon$2$$anonfun$4.apply(EventsByPersistenceIdSpec.scala:44)
[info]   at akka.persistence.couchbase.scaladsl.EventsByPersistenceIdSpec$$anonfun$1$$anonfun$apply$mcV$sp$2$$anon$2$$anonfun$4.apply(EventsByPersistenceIdSpec.scala:45)
[info]   at akka.testkit.TestKitBase$class.poll$2(TestKit.scala:312)
[info]   at akka.testkit.TestKitBase$class.awaitAssert(TestKit.scala:329)
[info]   at akka.testkit.TestKit.awaitAssert(TestKit.scala:896)
[info]   at akka.persistence.couchbase.scaladsl.AbstractCouchbaseSpec$Setup$class.readingOurOwnWrites(AbstractCouchbaseSpec.scala:70)
[info]   at akka.persistence.couchbase.scaladsl.EventsByPersistenceIdSpec$$anonfun$1$$anonfun$apply$mcV$sp$2$$anon$2.readingOurOwnWrites(EventsByPersistenceIdSpec.scala:34)
[info]   at akka.persistence.couchbase.scaladsl.EventsByPersistenceIdSpec$$anonfun$1$$anonfun$apply$mcV$sp$2$$anon$2.<init>(EventsByPersistenceIdSpec.scala:39)
[info]   at akka.persistence.couchbase.scaladsl.EventsByPersistenceIdSpec$$anonfun$1$$anonfun$apply$mcV$sp$2.apply(EventsByPersistenceIdSpec.scala:34)
[info]   at akka.persistence.couchbase.scaladsl.EventsByPersistenceIdSpec$$anonfun$1$$anonfun$apply$mcV$sp$2.apply(EventsByPersistenceIdSpec.scala:34)
[info]   at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
[info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:22)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:20)
[info]   at org.scalatest.WordSpecLike$$anon$1.apply(WordSpecLike.scala:1078)
[info]   at akka.testkit.WithLogCapturing$$anonfun$1.apply(WithLogCapturing.scala:37)
[info]   at akka.testkit.WithLogCapturing$$anonfun$1.apply(WithLogCapturing.scala:35)
[info]   at akka.testkit.EventFilter.intercept(TestEventListener.scala:111)
[info]   at akka.testkit.WithLogCapturing$class.withFixture(WithLogCapturing.scala:35)
[info]   at akka.persistence.couchbase.scaladsl.AbstractCouchbaseSpec.withFixture(AbstractCouchbaseSpec.scala:18)
```

**Comment by johanandren** [comment]
A different one: 

```
info] - must find existing events *** FAILED *** (10 seconds, 147 milliseconds)
[info]   java.lang.AssertionError: assertion failed: expected OnNext(1-1), found OnComplete
[info]   at scala.Predef$.assert(Predef.scala:170)
[info]   at akka.testkit.TestKitBase$class.expectMsg_internal(TestKit.scala:403)
[info]   at akka.testkit.TestKitBase$class.expectMsg(TestKit.scala:379)
[info]   at akka.testkit.TestKit.expectMsg(TestKit.scala:896)
[info]   at akka.stream.testkit.TestSubscriber$ManualProbe$$anonfun$expectNextN$1.apply(StreamTestKit.scala:388)
[info]   at akka.stream.testkit.TestSubscriber$ManualProbe$$anonfun$expectNextN$1.apply(StreamTestKit.scala:388)
[info]   at scala.collection.Iterator$class.foreach(Iterator.scala:891)
[info]   at scala.collection.AbstractIterator.foreach(Iterator.scala:1334)
[info]   at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
[info]   at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
[info]   at akka.stream.testkit.TestSubscriber$ManualProbe.expectNextN(StreamTestKit.scala:388)
[info]   at akka.stream.testkit.TestSubscriber$ManualProbe.expectNext(StreamTestKit.scala:358)
[info]   at akka.persistence.couchbase.scaladsl.EventsByPersistenceIdSpec$$anonfun$1$$anonfun$apply$mcV$sp$1$$anon$1$$anonfun$3.apply(EventsByPersistenceIdSpec.scala:26)
[info]   at akka.persistence.couchbase.scaladsl.EventsByPersistenceIdSpec$$anonfun$1$$anonfun$apply$mcV$sp$1$$anon$1$$anonfun$3.apply(EventsByPersistenceIdSpec.scala:30)
```

[log.txt](https://github.com/akka/akka-persistence-couchbase/files/2735946/log.txt)

**Comment by johanandren** [comment]
Actually seems to be caused by pr #185
