### ISSUE TITLE
FAILED: CouchbaseSessionTest index creation

### ISSUE THREAD

**Issue by johanandren** [akka/akka-persistence-couchbase#95]
Just started seeing this. @ygree did you see it before?

```
[error] Test akka.stream.alpakka.couchbase.javadsl.CouchbaseSessionTest failed: com.couchbase.client.core.CouchbaseException: Error creating primary index: [{"msg":"GSI CreatePrimaryIndex() - cause: Encounter errors during create index.  Error=Bucket does not exist or temporarily unavailable for creating new index. Please retry the operation at a later time (err=Bucket does not exist or temporarily unavailable for creating new index. Please retry the operation at a later time.).\n.","code":5000}], took 0.0 sec
[error]     at com.couchbase.client.java.bucket.DefaultAsyncBucketManager$27$1$1$1.call(DefaultAsyncBucketManager.java:743)
[error]     at com.couchbase.client.java.bucket.DefaultAsyncBucketManager$27$1$1$1.call(DefaultAsyncBucketManager.java:733)
```

**Comment by johanandren** [comment]
Seeing this repeatedly with now.

```
2018-11-30 10:00:57 [pool-1-thread-1] WARN  c.c.client.core.env.CoreEnvironment - More than 1 Couchbase Environments found (2), this can have severe impact on performance and stability. Reuse environments!
[error] Test akka.stream.alpakka.couchbase.javadsl.CouchbaseSessionTest failed: com.couchbase.client.core.CouchbaseException: Error creating primary index: [{"msg":"GSI CreatePrimaryIndex() - cause: Encounter errors during create index.  Error=Bucket does not exist or temporarily unavailable for creating new index. Please retry the operation at a later time (err=Bucket does not exist or temporarily unavailable for creating new index. Please retry the operation at a later time.).\n.","code":5000}], took 0.0 sec
```

**Comment by johanandren** [comment]
Ah, it creates the bucket specifically for that test, but it doesn't ensure the bucket is actually completely created yet when the create index is called. Would be good if you could look into that @ygree
